//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiayOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int sohd { get; set; }
        public int magiay { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual GIAY GIAY { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
