//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiayOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAY
    {
        public GIAY()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.CTHDs = new HashSet<CTHD>();
            this.SaleOffs = new HashSet<SaleOff>();
        }
    
        public int C_id { get; set; }
        public string magiay { get; set; }
        public string tengiay { get; set; }
        public string gioitinh { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> soluong { get; set; }
        public string hang { get; set; }
        public byte[] hinh { get; set; }
        public string chitiet { get; set; }
        public Nullable<decimal> gia { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual ICollection<SaleOff> SaleOffs { get; set; }
    }
}
