//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiayOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAY
    {
        public GIAY()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.IMAGES = new HashSet<IMAGE>();
            this.SALEOFFs = new HashSet<SALEOFF>();
            this.BANGSIZEs = new HashSet<BANGSIZE>();
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int magiay { get; set; }
        public string tengiay { get; set; }
        public string gioitinh { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> soluong { get; set; }
        public string hang { get; set; }
        public string hinh { get; set; }
        public string chitiet { get; set; }
        public Nullable<decimal> gia { get; set; }
        public Nullable<int> danhgia { get; set; }
        public Nullable<int> soluotdanhgia { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual ICollection<IMAGE> IMAGES { get; set; }
        public virtual ICollection<SALEOFF> SALEOFFs { get; set; }
        public virtual ICollection<BANGSIZE> BANGSIZEs { get; set; }
        public virtual ICollection<CTHD> CTHDs { get; set; }
    }
}
