//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiayOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public TAIKHOAN()
        {
            this.BINHLUANs = new HashSet<BINHLUAN>();
            this.HOADONs = new HashSet<HOADON>();
            this.DANHGIAs = new HashSet<DANHGIA>();
        }
    
        public int C_id { get; set; }
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public string hoten { get; set; }
        public string email { get; set; }
        public string gioitinh { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<System.DateTime> ngaydk { get; set; }
        public string avatar { get; set; }
        public Nullable<decimal> doanhthu { get; set; }
        public string quoctich { get; set; }
    
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
    }
}
