//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiayOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANCHU
    {
        public string tendangnhap { get; set; }
        public string gmail { get; set; }
        public string matkhau { get; set; }
        public string sdt { get; set; }
    }
}
