//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiayOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKE
    {
        public int id { get; set; }
        public Nullable<decimal> tongdoanhthu { get; set; }
        public Nullable<int> thang { get; set; }
        public Nullable<int> nam { get; set; }
        public Nullable<int> tongdonhang { get; set; }
        public Nullable<int> nguoidungmoi { get; set; }
        public Nullable<decimal> giatritrungbinh { get; set; }
    }
}
